### ISSUE TITLE
Does Not Check If User Can Access Problem

### ISSUE THREAD

**Issue by 0foxes** [plasmatic1/autocpp#2]
I think the layout of the best submissions page may have changed.

```
Traceback (most recent call last):
  File "main.py", line 74, in <module>
    check_problem(problem_id)
  File "main.py", line 38, in check_problem
    info = download_subs(TARGET_HANDLE, problem_id)
  File "/home/username/Downloads/autocpp/problem.py", line 82, in download_subs
    subs = get_solved(problem_id)
  File "/home/username/Downloads/autocpp/problem.py", line 59, in get_solved
    cur_subs = get_solved_page(problem_id, page_no)
  File "/home/username/Downloads/autocpp/problem.py", line 41, in get_solved_page
    sub_id = regex_find_href(tag, r'/submission/(\d+)').group(1)
  File "/home/username/Downloads/autocpp/problem.py", line 29, in regex_find_href
    return re.search(exp, tag.find('a', {'href': re.compile(exp)})['href'])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by 0foxes** [comment]
Upon further investigation, I think the issue stems from [this line](https://github.com/plasmatic1/autocpp/blob/master/main.py#L15). Even though it returns a list of the "solved problems", problems that only been partially solved by the user are also included.

When the program then tries to download other submissions for the problem, it raises a TypeError and crashes.

**Comment by 0foxes** [comment]
Closed by https://github.com/plasmatic1/autocpp/pull/5
